bear/main.py.in

Changed to use next([]) instead as this will work on both Python 2 and 3.
This fixes the error that occurs after the compilation process finishes:
```
bear: Something unexpected had happened.
Traceback (most recent call last):
File "/usr/bin/bear", line 63, in main
return capture(args)
File "/usr/bin/bear", line 107, in capture
json.dump(list(entries), handle, sort_keys=True, indent=4)
File "/usr/bin/bear", line 90, in <genexpr>
return (entry for entry in itertools.chain(previous, current)
File "/usr/bin/bear", line 169, in format_entry
atoms = classify_parameters(entry['command'])
File "/usr/bin/bear", line 383, in classify_parameters
args.next()
AttributeError: 'list_iterator' object has no attribute 'next'
```

Fix incompatible use of [].next() on Python 3

---

libear/ear.c

This should fix #215, hopefully. I've tested this using `bear --libear` with the new libear.dylib (which was quite convenient, but I'm unsure if that was something I was supposed to use) on a couple of projects and it seems to work OK for most cases, whereas it didn't work at all before. I did run into one issue when trying to pass address sanitizer flags to ld but I'm unsure if that's a problem with Bear or this particular project's Makefile, so I'll try to double check that tomorrow.

Don't cache the value of _NSGetEnviron on macOS

---

bear/bear.py
test/functional/cases/end-to-end/qmake.ft

Hi,
When I use Bear to capture cross-platform builds, I encountered a flag (-mabi=...) that will cause clangd to fail. Therefore, I added a Bear argument to add custom filters for flags. Figured it could be useful for others as well. so here it is.

add --remove-flags argument

---

CMakeLists.txt

* CMakeLists.txt (USE_SHELL_COMPLETION) : Cmake option to disable
conditionally bash-completions dependency.
shell-completion add an extra dependency that cannot be satisfied in all machines (user without sudo privileges.

Add an option to use bash-completions conditionally.

---

source/citnames/source/Configuration.cc

Fixing build error for Alpine Linux Edge, which uses musl libc.

citnames: size_t is not always an unsigned long

---

README.md

- Should be removed once all major package manager updated to 3.0.
(You might instead prefer to have this as part of your troubleshooting wiki, but I can't modify the wiki.
In that case please feel free to close my pr.)

Temp workaround note for old 2.4 release

---

source/intercept/source/report/libexec/lib.cc

Fixes https://github.com/rizsotto/Bear/issues/469
This simply sets `errno = 0` at the end of libexec.so's `on_load`

Fix #469: set errno to 0 after libexec's on_load

---

source/intercept/CMakeLists.txt

Linking C++ code with the C linker causes a missing vtable for in __cxxabiv1::__class_type_info, referenced from runtime type information in el::Linker and el::Resolver. Linking this library with clang++ instead fixes the issue.
From the git log, it was not clear to me why LINKER_LANGUAGE "C" was introduced in the first place. It no longer seems to be necessary.
Full error is:
```
/usr/bin/clang  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -dynamiclib -Wl,-headerpad_max_install_names -o libexec.dylib -install_name @rpath/libexec.dylib CMakeFiles/exec.dir/source/report/libexec/lib.cc.o CMakeFiles/exec.dir/source/report/libexec/std.cc.o CMakeFiles/exec_a.dir/source/report/libexec/Buffer.cc.o …
```

Fix undefined __cxxabiv1::__class_type_info vtable

---

CMakeLists.txt

close #479
add -DCMAKE_PROJECT_INCLUDE argument to allow user injecting custom code into source subproject without modifying it's source code.
for example, user may want to link static libraries, they can write following code to `project-after.cmake`
```
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
```
then pass `-DCMAKE_PROJECT_INCLUDE=project-after.cmake` to cmake command
then project-after.cmake will be automatically run after `project()` command
Reference: https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_INCLUDE.html
Signed-off-by: leleliu008 <leleliu008@gmail.com>

add -DCMAKE_PROJECT_INCLUDE argument

---

test/cases/intercept/preload/errno_reset.c
test/cases/intercept/preload/posix/execvpe/success.c

Include <stdio.h> for printf and define _GNU_SOURCE for execvpe.
Future compilers will not support implicit function declartions by default, causing these tests to fail to build.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

Avoid implicit function declarations in tests, for C99 compatibility

---

source/CMakeLists.txt

Facing the bug same as #471 on fmt-10.0.0 version, do a quick fix.
gentoo downstream bug report: https://bugs.gentoo.org/906082

dependency: fix fmt 10.0.0 incompatibilities

---

source/citnames/source/semantic/ToolAny.cc
source/citnames/source/semantic/ToolExtendingWrapper.cc
source/libflags/source/Flags.cc
source/libsys/source/Guard.cc
source/libsys/source/Process.cc

GCC 14 drops some transitive includes within libstdc++.
Explicitly include <algorithm> for std::find.

Add missing <algorithm> include for std::find

---

source/citnames/source/semantic/Semantic.cc

Fixes https://github.com/rizsotto/Bear/issues/542
`fmt` supports formatting `fs::path` through `fmt/std.h`.

Use fmt/std to format std::path

---

source/citnames/source/semantic/ToolGcc.cc

The value of the `-include` param does not have to be separated.

citnames: Allow for include flag glued to the parameter

---

source/intercept/source/collect/db/EventsDatabaseWriter.cc

hopefully this condition based on GOOGLE_PROTOBUF_VERSION will save the day

always_print_primitive_fields only if GOOGLE_PROTOBUF_VERSION < 5026000 ref #566

---

source/intercept/CMakeLists.txt

Or else `bear` does not intercept the calls to `gfortran` in MacOS.

Add `gfortran` as a compiler wrapper

---

source/citnames/source/semantic/Parsers.h
source/citnames/source/semantic/Semantic.cc

fmt::join() was moved into fmt/ranges.h since fmt v11, so include this header for using fmt::join(). otherwise, we'd have following compilation failure when building Bear with fmt v11 and up:
```
/builddir/build/BUILD/bear-3.1.4-build/Bear-3.1.4/source/citnames/source/semantic/Parsers.h:255:73: error: ‘join’ is not a member of ‘fmt’
255 |                             fmt::format("Failed to recognize: {}", fmt::join(remainder.begin(), remainder.end(), ", "))
|                                                                         ^~~~
```

citnames: include fmt/ranges.h for using fmt::join()

---

.github/workflows/build_on_arch.yml

ci: run alpine image against aarch64

---

source/citnames/source/semantic/ToolGcc.cc
source/citnames/test/ToolGccTest.cc

This pull request modifies the regex for recognized GCC compiler calls to allow pre/postfixes to `cc` and `c++` in the same manner as already implemented e.g. for `gcc` (though explicitly excluding `cc1`, which otherwise would also be matched). This matches e.g. the previously missing `x86_64-pc-linux-gnu-cc` and `x86_64-pc-linux-gnu-c++` compiler calls that are present on my system (Gentoo, sys-devel/gcc-13.2.1_p20240210).
More specifically, I've encountered the issue of such compiler call being unrecognized when applying Bear to the compilation of Neomutt and using the `.configure` command as used by portage for the Neomutt ebuild (to align with target build process), which then employs `x86_64-pc-linux-gnu-cc` as compiler call. While this is simply a symlink to …

citnames: allow pre/postfixes to cc & c++ compiler calls

---

rust/Cargo.toml
rust/bear/Cargo.toml
rust/bear/src/semantic/interpreters/gcc.rs
rust/bear/src/semantic/interpreters/generic.rs
rust/bear/src/semantic/interpreters/matchers/source.rs
rust/bear/tests/intercept.rs

Hello, I am glad to know that bear is being rewritten in Rust and it sounds interesting.
This patch removes uses of lazy_static since it is going to be deprecated (see https://github.com/rust-lang-nursery/lazy-static.rs/issues/214). The std library now supports OnceCell and OnceLock as alternatives.

Replace lazy_static with OnceLock

---

CMakeLists.txt

This change ensures that `BearSource` is rebuilt whenever its sources are modified. The `BUILD_ALWAYS` option in CMake's `ExternalProject` module enforces this behavior. For more details, see the CMake documentation
https://cmake.org/cmake/help/latest/module/ExternalProject.html.

Add `BUILD_ALWAYS` to ensure `BearSource` rebuilds

---

source/citnames/CMakeLists.txt
source/citnames/source/semantic/Build.cc
source/citnames/source/semantic/Common.cc
source/citnames/source/semantic/Common.h
source/citnames/source/semantic/ToolGcc.cc
source/citnames/source/semantic/ToolIntelFortran.cc
source/citnames/source/semantic/ToolIntelFortran.h
source/citnames/test/ToolIntelFortranTest.cc
source/intercept/CMakeLists.txt

I'm a member of [Codee](https://www.codee.com/) and we are developing a tool that requires the compile commands generated with `bear` to work also with Intel Fortran compilers. We extended `bear` functionality and considered that it would be useful for the project.
This PR adds a new `citnames` Tool to support Intel Fortran compilers `ifx` and `ifort`. I used the same approach that is done in the ToolGcc, classifying the most relevant compiler/linker/preprocessor flags according to the official [intel documentation](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2025-0/alphabetical-option-list.html).
I took advantage and factorized some functionality that is common to both GCC and IntelFortran.
It was tested with 2023.2.0 and 2025.0.0 Intel Fortran …

Add Intel Fortran compilers to the citnames Tools

---

source/citnames/source/semantic/ToolGcc.cc

When building gcc and g++, the compiler core is first built as xgcc/xg++, and these are then used to compile other components (e.g. libgcc or libstdc++). Since xgcc/xg++ were not recognized by bear, many files were missing from compile_commands.json when building gcc.
../configure --disable-bootstrap --disable-multilib --enable-languages=c,c++
bear -- make
jq 'length' compile_commands.json
Fixes: https://github.com/rizsotto/Bear/issues/563

citnames: add xgcc and xg++

---

source/bear/man/bear.1
source/bear/man/bear.1.md
source/bear/source/Application.cc
source/config.h.in
source/libflags/source/Flags.cc
source/libflags/test/FlagsTest.cc
test/cases/intercept/wrapper/shell_enable_network_proxy.sh

Create a new flag `--enable-network-proxy` that allows the user to specifically use the HTTP proxy environment variables that gRPC takes underneath. Otherwise, these variables are unset by default, avoiding the known error:
```wrapper: failed with: gRPC call failed: failed to connect to all addresses```

Disable network proxies by default

---

source/citnames/source/semantic/ToolWrapper.cc
source/citnames/test/ToolWrapperTest.cc

This adds support for the [sccache](https://github.com/mozilla/sccache) compiler wrapper by treating it as a variant of `ccache`.
I added some basic tests derived from the `ccache` tests, and also updated the `is_distcc_query` tests while I was at it because they were calling `is_ccache_query` instead of `is_distcc_query` (which I assume was what was actually meant to be tested).

Add support for sccache
